branches: main
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalCommits
      releaseRules:
        - type: docs
          release: patch
        - type: ci
          release: patch
        - type: major
          release: major
  - '@semantic-release/git'
  - '@semantic-release/github'
