output "workload_identity_token" {
  value       = data.environment_variable.tfc_workload_identity_token.value
  description = "The value of the workload identity token generated by Terraform Enterprise."
}
