name: Merge Dependabot

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-20.04
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.5.1
      - name: Enable Auto-merge for Dependabot PRs
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' }}
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge --auto --squash "$PR_URL"
      - name: Approve a PR
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.AUTO_COMMIT_TOKEN }}
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          gh pr review --approve "$PR_URL"
