name: Generate Docs

on:
  pull_request

permissions:
  contents: write

jobs:
  docs:
    name: Generate Docs
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.PULL_REQUEST_RW }}
    - name: Generate Docs
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "false"
