name: Generate Docs

on:
  pull_request

permissions:
  contents: read

jobs:
  docs:
    name: Generate Docs
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Generate Docs
      uses: terraform-docs/gh-actions@v1.0.0
