name: Format Code

on:
  pull_request

permissions:
  contents: read

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.0.0"
    - name: Format Code
      run: |
        terraform fmt -recursive .
